cd spdlog/build/
cmake .. -DSPDLOG_BUILD_EXAMPLE=OFF -DSPDLOG_BUILD_EXAMPLES=OFF -DSPDLOG_BUILD_EXAMPLE_HO=OFF -DSPDLOG_BUILD_TESTING=OFF -DSPDLOG_BUILD_TESTIS=OFF -DSPDLOG_BUILD_TESTS_HO=OFF -DBUILD_TESTING=OFF -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" -DCMAKE_C_FLAGS="${C_FLAGS}" ${CMAKE_OPTIONS}
make ${CMAKE_MAKE_OPTIONS}
sudo make install
