import { UrlParameterParser } from "tc-shared/settings";
import { ConnectionHandler } from "tc-shared/ConnectionHandler";
import { ConnectRequestData } from "tc-shared/ipc/ConnectHandler";
import "svg-sprites/client-icons";
import "../css/load-css";
import "./proto";
import "./profiles/ConnectionProfile";
import "./update/UpdaterWeb";
import "./file/LocalIcons";
import "./connection/CommandHandler";
import "./connection/ConnectionBase";
import "./connection/rtc/Connection";
import "./connection/rtc/video/Connection";
import "./video/VideoSource";
import "./media/Video";
import "./ui/AppController";
import "./ui/frames/menu-bar/MainMenu";
import "./ui/modal/connect/Controller";
import "./ui/modal/video-viewer/Controller";
import "./ui/modal/avatar-upload/Controller";
import "./ui/elements/ContextDivider";
import "./ui/elements/Tab";
import "./clientservice";
import "./text/bbcode/InviteController";
import "./text/bbcode/YoutubeController";
export declare function handleNativeConnectRequest(url: URL): void;
export declare function handleConnectRequest(serverAddress: string, serverUniqueId: string | undefined, parameters: UrlParameterParser): Promise<void>;
export declare function handle_connect_request(properties: ConnectRequestData, _connection: ConnectionHandler): void;
