    #define XMACRO_EV_UNDEF
#ifndef XMACRO_EV
#define XMACRO_EV(a, b, c, d)
#endif
#ifndef XMACRO_LAGACY_EV
    #define XMACRO_LAGACY_EV_UNDEF
    #define XMACRO_LAGACY_EV(var, gr, spec)
#endif

XMACRO_EV("server",  "edit",             QEVENTGROUP_SERVER,         QEVENTSPECIFIER_SERVER_EDIT)
XMACRO_EV("client",  "poke",             QEVENTGROUP_CLIENT_MISC,    QEVENTSPECIFIER_CLIENT_MISC_POKE)
XMACRO_EV("client",  "update",           QEVENTGROUP_CLIENT_MISC,    QEVENTSPECIFIER_CLIENT_MISC_UPDATE)
XMACRO_EV("client",  "command",          QEVENTGROUP_CLIENT_MISC,    QEVENTSPECIFIER_CLIENT_MISC_COMMAND)
XMACRO_EV("client",  "join",             QEVENTGROUP_CLIENT_VIEW,    QEVENTSPECIFIER_CLIENT_VIEW_JOIN)
XMACRO_EV("client",  "leave",            QEVENTGROUP_CLIENT_VIEW,    QEVENTSPECIFIER_CLIENT_VIEW_LEAVE)
XMACRO_EV("client",  "switch",           QEVENTGROUP_CLIENT_VIEW,    QEVENTSPECIFIER_CLIENT_VIEW_SWITCH)
XMACRO_EV("client",  "add",              QEVENTGROUP_CLIENT_GROUPS,  QEVENTSPECIFIER_CLIENT_GROUPS_ADD)
XMACRO_EV("client",  "remove",           QEVENTGROUP_CLIENT_GROUPS,  QEVENTSPECIFIER_CLIENT_GROUPS_REMOVE)
XMACRO_EV("client",  "change",           QEVENTGROUP_CLIENT_GROUPS,  QEVENTSPECIFIER_CLIENT_GROUPS_CHANNEL_CHANGED)
XMACRO_EV("chat",    "composing",        QEVENTGROUP_CHAT,           QEVENTSPECIFIER_CHAT_COMPOSING)
XMACRO_EV("chat",    "receive_server",   QEVENTGROUP_CHAT,           QEVENTSPECIFIER_CHAT_MESSAGE_SERVER)
XMACRO_EV("chat",    "receive_channel",  QEVENTGROUP_CHAT,           QEVENTSPECIFIER_CHAT_MESSAGE_CHANNEL)
XMACRO_EV("chat",    "receive_private",  QEVENTGROUP_CHAT,           QEVENTSPECIFIER_CHAT_MESSAGE_PRIVATE)
XMACRO_EV("chat",    "close",            QEVENTGROUP_CHAT,           QEVENTSPECIFIER_CHAT_CLOSED)
XMACRO_EV("channel", "create",           QEVENTGROUP_CHANNEL,        QEVENTSPECIFIER_CHANNEL_CREATE)
XMACRO_EV("channel", "edit",             QEVENTGROUP_CHANNEL,        QEVENTSPECIFIER_CHANNEL_EDIT)
XMACRO_EV("channel", "desc",             QEVENTGROUP_CHANNEL,        QEVENTSPECIFIER_CHANNEL_DESC_EDIT)
XMACRO_EV("channel", "password",         QEVENTGROUP_CHANNEL,        QEVENTSPECIFIER_CHANNEL_PASSWORD_EDIT)
XMACRO_EV("channel", "move",             QEVENTGROUP_CHANNEL,        QEVENTSPECIFIER_CHANNEL_MOVE)
XMACRO_EV("channel", "delete",           QEVENTGROUP_CHANNEL,        QEVENTSPECIFIER_CHANNEL_DELETED)
XMACRO_EV("music",   "queue",            QEVENTGROUP_MUSIC,          QEVENTSPECIFIER_MUSIC_QUEUE)
XMACRO_EV("music",   "player",           QEVENTGROUP_MUSIC,          QEVENTSPECIFIER_MUSIC_PLAYER)


XMACRO_LAGACY_EV("server",       QEVENTGROUP_SERVER,      QEVENTSPECIFIER_SERVER_EDIT)
XMACRO_LAGACY_EV("server",       QEVENTGROUP_CLIENT_VIEW, QEVENTSPECIFIER_CLIENT_VIEW_JOIN)
XMACRO_LAGACY_EV("server",       QEVENTGROUP_CLIENT_VIEW, QEVENTSPECIFIER_CLIENT_VIEW_LEAVE)

XMACRO_LAGACY_EV("channel",      QEVENTGROUP_CLIENT_VIEW, QEVENTSPECIFIER_CLIENT_VIEW_JOIN)
XMACRO_LAGACY_EV("channel",      QEVENTGROUP_CLIENT_VIEW, QEVENTSPECIFIER_CLIENT_VIEW_LEAVE)
XMACRO_LAGACY_EV("channel",      QEVENTGROUP_CLIENT_VIEW, QEVENTSPECIFIER_CLIENT_VIEW_SWITCH)
XMACRO_LAGACY_EV("channel",      QEVENTGROUP_CHANNEL,     QEVENTSPECIFIER_CHANNEL_CREATE)
XMACRO_LAGACY_EV("channel",      QEVENTGROUP_CHANNEL,     QEVENTSPECIFIER_CHANNEL_EDIT)
XMACRO_LAGACY_EV("channel",      QEVENTGROUP_CHANNEL,     QEVENTSPECIFIER_CHANNEL_DELETED)
XMACRO_LAGACY_EV("channel",      QEVENTGROUP_CHANNEL,     QEVENTSPECIFIER_CHANNEL_MOVE)
XMACRO_LAGACY_EV("channel",      QEVENTGROUP_CHANNEL,     QEVENTSPECIFIER_CHANNEL_DESC_EDIT)
XMACRO_LAGACY_EV("channel",      QEVENTGROUP_CHANNEL,     QEVENTSPECIFIER_CHANNEL_PASSWORD_EDIT)

XMACRO_LAGACY_EV("textserver",   QEVENTGROUP_CHAT,        QEVENTSPECIFIER_CHAT_MESSAGE_SERVER)
XMACRO_LAGACY_EV("textchannel",  QEVENTGROUP_CHAT,        QEVENTSPECIFIER_CHAT_MESSAGE_CHANNEL)
XMACRO_LAGACY_EV("textprivate",  QEVENTGROUP_CHAT,        QEVENTSPECIFIER_CHAT_MESSAGE_PRIVATE)

#ifdef XMACRO_EV_UNDEF
    #undef XMACRO_EV_UNDEF
    #undef XMACRO_EV
#endif
#ifdef XMACRO_LAGACY_EV_UNDEF
    #undef XMACRO_LAGACY_EV_UNDEF
    #undef XMACRO_LAGACY_EV
#endif